logs:
    dir_logs: /home/abhijit/anaconda3/VizWiz-VQA-PyTorch-master/logs
annotations:
    dir: /home/abhijit/anaconda3/VizWiz-VQA-PyTorch-master/data/Annotations
    top_ans: 3000
    max_length: 26
    min_count_word: 0
    path_vocabs: ./vocabs.json
images:
    dir: /home/abhijit/anaconda3/VizWiz-VQA-PyTorch-master/data/train
    arch: ResNet152
    mode: att
    img_size: 448
    preprocess_batch_size: 4
    preprocess_data_workers: 4
    path_features: ./resnet101.h5
model:
# Could be added new architectures and hyper-parameters like activations etc
    pretrained_model:  #./logs/... # leave empty if no pretrained model is available
    seq2vec:
        dropout: 0.25
        emb_size: 300
    pooling:
        dim_v: 2048
        dim_q: 1024
        dim_h: 1024
        dropout_v: 0.25
        dropout_q: 0.25
    classifier:
        dropout: 0.5
    attention:
        glimpses: 4
        mid_features: 512
        dropout: 0.5
training:
    train_split: train
    lr: 0.001
    batch_size: 128
    epochs: 50
    data_workers: 4

prediction:
    model_path: /home/abhijit/anaconda3/VizWiz-VQA-PyTorch-master/logs/resnet101_4/final_log.pth
    split: test
    submission_file: ./default_pred.json
    submission_file_2: ./answerability.json

